### ISSUE TITLE
danwchan: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by danwchan** [goyalsid/phageParser#30]
Hi, I'm new to python development. I've done a little coding to clean up extracted spreadsheets for use in CellHTS2. I want to see if I can apply myself to something more related to my field (I study Microbiology... mostly wet lab work, infectious disease) and improve my python skills.

I am both interested in the scientific scope of this project and the educational possibility of doing coding! Let me know how I should start integrating myself into this work.<p><br><blockquote>This issue was created by @danwchan via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by mbonsma** [comment]
Hello and welcome! I'm Madeleine, one of the project leads on this project since February. Cleaning up data files is something we've done a lot in this project so far, so your experience sounds very relevant. 

As for what to contribute to, it's really up to you - anything in the Issues section is up for improvement and contributions. You can also make new issues as things come up or if you have ideas for improvements. Issues 27 and 29 are two newer ones that might be fun to try - 29 especially is a data parsing issue. 

If you want to get a feel for what's been done so far, try out the existing code following the instructions in the ReadMe (there are two complementary but different sets of instructions). And let me know if you have any questions!
