### ISSUE TITLE
Can use bower to manage front end depencies

### ISSUE THREAD

**Issue by darwinhang** [goyalsid/phageParser#49]
I found this project from the list of mozillascience projects. It looks like most of the work is being done by Python, but Javascript is taking up the majority of this repo.  

![screen shot 2015-06-20 at 2 52 43 pm](https://cloud.githubusercontent.com/assets/2671518/8268999/0b606ca0-175c-11e5-8da1-3c6bb9789e74.png)

cytoscape.js is being developed separately, so a Javascript package manager (such as bower or npm) could be used to manage that dependency (cytoscape.js). This way, only the people that wanted to use the visualization tools would have to download it.

[Bower](https://github.com/bower/bower) does rely on node.js. You may be trying to reduce the number of dependencies required to build phageParser.

**Comment by mbonsma** [comment]
I agree. This happened because I thought it would be simple to just throw cytoscape.js into this repo. I was planning to just remove it completely, but what you're talking about sounds like a good solution, because, you're right, not everyone will want to use the visualization branch. @darwinhang, are you willing/able to implement this?

**Comment by darwinhang** [comment]
@mbonsma Yes, I'll set up a PR for this.

**Comment by mbonsma** [comment]
Done - thanks @darwinhang!
